export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const SELECT_LOGIN_FORM = 'SELECT_LOGIN_FORM';
export const SELECT_SIGNUP_FORM = 'SELECT_SIGNUP_FORM';
export const TOGGLE_SHOW_PASSWORD = 'TOGGLE_SHOW_PASSWORD';
export const VALID_EMAIL = 'VALID_EMAIL';
export const INVALID_EMAIL = 'INVALID_EMAIL';

export const INVALID_FIRST_NAME = 'INVALID_FIRST_NAME';
export const INVALID_LAST_NAME = 'INVALID_LAST_NAME';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const MATCH_PASSWORDS = 'MATCH_PASSWORDS';


export const USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTER';
export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const PROCEED_TO_ACCOUNT_VERIFICATION = 'PROCEED_TO_ACCOUNT_VERIFICATION';
export const ENABLE_OTP_REGENERATION = 'ENABLE_OTP_REGENERATION';
export const DISABLE_OTP_REGENERATION = 'DISABLE_OTP_REGENERATION';

export const MAKE_API_CALL_TO_GET_NEW_OTP = 'MAKE_API_CALL_TO_GET_NEW_OTP';
export const OTP_REGENERATION_SUCCESSFUL = 'OTP_REGENERATION_SUCCESSFUL'